namespace PjtControlEPP.Formularios
{
    partial class FrmConsultaAutorizacion
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn6 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn3 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn7 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            this.dtgEPP = new Telerik.WinControls.UI.RadGridView();
            this.consultaautorizacionBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.consultas = new PjtControlEPP.Consultas();
            this.consultaautorizacionTableAdapter = new PjtControlEPP.ConsultasTableAdapters.consultaautorizacionTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultaautorizacionBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultas)).BeginInit();
            this.SuspendLayout();
            // 
            // dtgEPP
            // 
            this.dtgEPP.Location = new System.Drawing.Point(12, 12);
            // 
            // 
            // 
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "idfactura";
            gridViewDecimalColumn1.HeaderText = "NO FACTURA";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "idfactura";
            gridViewDecimalColumn1.Width = 80;
            gridViewTextBoxColumn1.FieldName = "NombreEmpleado";
            gridViewTextBoxColumn1.HeaderText = "NOMBRE EMPLEADO";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "NombreEmpleado";
            gridViewTextBoxColumn1.Width = 200;
            gridViewTextBoxColumn2.FieldName = "Cedula";
            gridViewTextBoxColumn2.HeaderText = "CEDULA";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "Cedula";
            gridViewTextBoxColumn2.Width = 100;
            gridViewTextBoxColumn3.FieldName = "OracleID";
            gridViewTextBoxColumn3.HeaderText = "ORACLE ID";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "OracleID";
            gridViewTextBoxColumn3.Width = 80;
            gridViewTextBoxColumn4.FieldName = "AreaTrabajo";
            gridViewTextBoxColumn4.HeaderText = "AREA DE TRABAJO";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Name = "AreaTrabajo";
            gridViewTextBoxColumn4.Width = 150;
            gridViewDecimalColumn2.DataType = typeof(int);
            gridViewDecimalColumn2.FieldName = "idproducto";
            gridViewDecimalColumn2.HeaderText = "ITEM";
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.Name = "idproducto";
            gridViewDecimalColumn2.Width = 80;
            gridViewTextBoxColumn5.FieldName = "nombreepp";
            gridViewTextBoxColumn5.HeaderText = "DESCRIPCION";
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.Name = "nombreepp";
            gridViewTextBoxColumn5.Width = 200;
            gridViewTextBoxColumn6.FieldName = "fechavence";
            gridViewTextBoxColumn6.HeaderText = "FECHA VENCE";
            gridViewTextBoxColumn6.IsAutoGenerated = true;
            gridViewTextBoxColumn6.Name = "fechavence";
            gridViewTextBoxColumn6.Width = 80;
            gridViewDecimalColumn3.DataType = typeof(int);
            gridViewDecimalColumn3.FieldName = "codigoautorizacion";
            gridViewDecimalColumn3.HeaderText = "CODIGO AUTORIZACION";
            gridViewDecimalColumn3.IsAutoGenerated = true;
            gridViewDecimalColumn3.Name = "codigoautorizacion";
            gridViewDecimalColumn3.Width = 100;
            gridViewTextBoxColumn7.FieldName = "observacion";
            gridViewTextBoxColumn7.HeaderText = "OBSERVACION";
            gridViewTextBoxColumn7.IsAutoGenerated = true;
            gridViewTextBoxColumn7.Name = "observacion";
            gridViewTextBoxColumn7.Width = 150;
            this.dtgEPP.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewDecimalColumn2,
            gridViewTextBoxColumn5,
            gridViewTextBoxColumn6,
            gridViewDecimalColumn3,
            gridViewTextBoxColumn7});
            this.dtgEPP.MasterTemplate.DataSource = this.consultaautorizacionBindingSource;
            this.dtgEPP.MasterTemplate.EnableFiltering = true;
            this.dtgEPP.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.dtgEPP.Name = "dtgEPP";
            this.dtgEPP.ReadOnly = true;
            this.dtgEPP.Size = new System.Drawing.Size(984, 537);
            this.dtgEPP.TabIndex = 0;
            this.dtgEPP.DoubleClick += new System.EventHandler(this.dtgEPP_DoubleClick_1);
            // 
            // consultaautorizacionBindingSource
            // 
            this.consultaautorizacionBindingSource.DataMember = "consultaautorizacion";
            this.consultaautorizacionBindingSource.DataSource = this.consultas;
            // 
            // consultas
            // 
            this.consultas.DataSetName = "Consultas";
            this.consultas.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // consultaautorizacionTableAdapter
            // 
            this.consultaautorizacionTableAdapter.ClearBeforeFill = true;
            // 
            // FrmConsultaAutorizacion
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.ClientSize = new System.Drawing.Size(1008, 561);
            this.Controls.Add(this.dtgEPP);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "FrmConsultaAutorizacion";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.FrmConsultaAutorizacion_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtgEPP)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultaautorizacionBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.consultas)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView dtgEPP;
        private Consultas consultas;
        private System.Windows.Forms.BindingSource consultaautorizacionBindingSource;
        private ConsultasTableAdapters.consultaautorizacionTableAdapter consultaautorizacionTableAdapter;



    }
}